# Generated by Django 4.2 on 2024-05-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcu',
            name='irrigationTime',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='mcu',
            name='sleepingTime',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='mcu',
            name='threshold',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
