# Generated by Django 4.2 on 2024-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mcu_irrigationtime_mcu_sleepingtime_mcu_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcu',
            name='name',
            field=models.CharField(default='esp', max_length=255, null=True),
        ),
    ]
